---
# the hostname here is the service name for your mysql app
apiVersion: v1
kind: Secret
metadata:
  name: hostname-mysql
stringData:
  hostname: mysql                   
apiVersion: v1
---
# this is password for your root mysql user
kind: Secret
metadata:
  name: mysql-secret                
type: kubernetes.io/basic-auth
stringData:
  password: prova
---
apiVersion: v1
kind: Secret
metadata:
  name: user-name
type: kubernetes.io/basic-auth
stringData:
  username: root
